task_manager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve

from task_manager import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls"))
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += [
    re_path(r"^media/(?P<path>.*)$", serve, {
        "document_root": settings.MEDIA_ROOT
    })
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path("__debug__/", include(debug_toolbar.urls)),

tasks/urls.py
from django.urls import path

from tasks.views import (
    UserLoginView,
    UserRegistrationView,
    UserPasswordChangeView,
    ProjectListView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TaskCreateView,
    ProjectTaskListView,
    ProfileDetailView,
    ProfileUpdateView,
    TaskListView,
    TaskDetailView,
    ProjectDetailView,
    JoinProjectView,
    GenerateCodeView,
    ChatMessagesView,
    LogoutView,
    TaskUpdateView,
    TaskDeleteView,
    IndexView
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("accounts/login/", UserLoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/register/", UserRegistrationView.as_view(), name="register"),
    path("accounts/password-change/", UserPasswordChangeView.as_view(), name="password-change"),
    path("projects/",
         ProjectListView.as_view(),
         name="project-list"
         ),
    path("projects/<int:pk>/",
         ProjectDetailView.as_view(),
         name="project-detail"
         ),
    path("projects/<int:pk>/project_tasks/",
         ProjectTaskListView.as_view(),
         name="project-task-list"),
    path("projects/<int:pk>/tasks/",
         TaskListView.as_view(),
         name="task-list"),
    path("projects/<int:pk>/tasks/<int:task_pk>/",
         TaskDetailView.as_view(),
         name="task-detail"),
    path("projects/<int:pk>/tasks/add/",
         TaskCreateView.as_view(),
         name="task-add"),
    path("projects/<int:pk>/tasks/<int:task_pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"),
    path("projects/<int:pk>/tasks/<int:task_pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),
    path("projects/create/",
         ProjectCreateView.as_view(),
         name="project-create"
         ),
    path("projects/<int:pk>/update/",
         ProjectUpdateView.as_view(),
         name="project-update"
         ),
    path("projects/<int:pk>/delete/",
         ProjectDeleteView.as_view(),
         name="project-delete"),
    path("projects/<int:pk>/invitation/",
         GenerateCodeView.as_view(),
         name="project-invitation"),
    path("projects/join/",
         JoinProjectView.as_view(),
         name="project-join"),
    path("projects/<int:pk>/chat/",
         ChatMessagesView.as_view(),
         name="project-chat"),
    path("profile/",
         ProfileDetailView.as_view(),
         name="profile-detail"
         ),
    path("profile/edit/",
         ProfileUpdateView.as_view(),
         name="profile-edit")
]

app_name = "tasks"

templates/includes/comments.html
<div class="comments">
    <p>{{ task.comments.count }} comment{{ task.comments.count|pluralize }}</p>
    <form action="" method="post" class="search-form">
      {% if user.is_authenticated %}
        <div class="comment-input">
        {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary btn-xs" type="submit">Comment</button>
        </div>
      {% endif %}
    </form>
    {% if comments %}
      <div>
        {% for comment in comments %}
          <div class="user-comment">
            <div class="row">
              <div class="col-sm-2">
                <h5>{% if comment.sender == request.user %}Me{% else %}{{ comment.sender.username }}{% endif %}</h5>
              </div>
              <div>{{ comment.date }}</div>
            </div>
            <div class="comment-message">
              <p>{{ comment.message }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <strong class="text-secondary">No comments yet...</strong>
    {% endif %}
  </div>

templates/includes/head.html
{% load static %}

<title>Task manager</title>
<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 11]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="description"
      content="Free Datta Able Admin Template come up with latest Bootstrap 4 framework with basic components, form elements and lots of pre-made layout options"/>
<meta name="keywords"
      content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, datta able, datta able bootstrap admin template, free admin theme, free dashboard template"/>
<meta name="author" content="CodedThemes"/>

<!-- Favicon icon -->
<link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">
<!-- fontawesome icon -->
<link rel="stylesheet" href="{% static 'assets/fonts/fontawesome/css/fontawesome-all.min.css' %}">
<!-- animation css -->
<link rel="stylesheet" href="{% static 'assets/plugins/animation/css/animate.min.css' %}">
<!-- vendor css -->
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<!-- dark mode css -->
<link rel="stylesheet" href="{% static 'assets/css/dark.css' %}">

templates/includes/navigation.html
{% load static %}

<header class="navbar pcoded-header navbar-expand-lg navbar-light">
  <div class="m-header">
    <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
    <a href="{% url 'tasks:index' %}" class="b-brand">
      <div class="b-bg">
        <img class="feather icon-trending-up">
      </div>
      <span class="b-title">Task manager</span>
    </a>
  </div>
  <a class="mobile-menu" id="mobile-header" href="javascript:">
  </a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
            class="feather icon-maximize"></i></a></li>
      {% if show_search %}
        <li class="nav-item">
          <div class="main-search">
            <div class="input-group">
              <form action="" method="get" class="search-form">
                {{ search_form }}
                <button type="submit" class="button-search">
                  <i class="feather icon-search input-group-text"></i>
                </button>
              </form>
            </div>
          </div>
        </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav ml-auto">
      <li>
        <label>
          <i class="icon feather icon-sun" id="theme-indicator"></i>
          <input type="checkbox" id="theme-switch" class="d-none">
        </label>
      </li>
      <li>
        <div class="dropdown drp-user">
          <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon feather icon-settings"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right profile-notification">
            <div class="pro-head">
              {% if user.is_authenticated %}
                {% if user.profile_image and user.profile_image.url %}
                  <img src="{{ user.profile_image.url }}" class="img-radius" alt="User-Profile-Image">
                {% else %}
                  <img src="{% static 'assets/images/user/anon.jpg' %}" class="img-radius" alt="User-Profile-Image">
                {% endif %}
              <span>{{ user.get_username }}</span>
                <a href="{% url 'tasks:logout' %}" class="dud-logout" title="Logout">
                  <i class="feather icon-log-out"></i>
                </a>
              {% endif %}
            </div>
            <ul class="pro-body">
              <li><a href="{% url 'tasks:profile-detail' %}" class="dropdown-item"><i class="feather icon-user"></i>
                  Profile</a></li>
              {% if request.user.is_authenticated %}
              <li>
                <a href="{% url 'tasks:password-change' %}" class="dropdown-item">
                  <i class="feather icon-edit"></i>Change Password
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</header>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
{% load static %}

<!-- Required Js -->
<script src="{% static 'assets/js/vendor-all.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/pcoded.min.js' %}"></script>
<script src="{% static 'assets/js/dark-mode.js' %}"></script>

templates/includes/sidebar.html
{% load static %}
<nav class="pcoded-navbar">
  <div class="navbar-wrapper">
    <div class="navbar-brand header-logo">
      <a href="{% url 'tasks:index' %}" class="b-brand">
        <div class="b-bg">
          <img src="{% static 'assets/images/logo.png' %}" class="img-radius img-logo">
        </div>
        <span class="b-title">Task Manager</span>
      </a>
      <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
    </div>
    <div class="navbar-content scroll-div">
      <ul class="nav pcoded-inner-navbar">
        <li class="nav-item pcoded-menu-caption">
          <label>Navigation</label>
        </li>
        <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" class="nav-item">
          <a href="{% url 'tasks:project-list' %}" class="nav-link ">
            <span class="pcoded-micon"><i class="feather icon-folder"></i></span><span class="pcoded-mtext">Projects</span>
          </a>
        </li>
        <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" class="nav-item">
          <a href="{% url 'tasks:project-join' %}" class="nav-link ">
            <span class="pcoded-micon"><i class="feather icon-plus"></i></span><span class="pcoded-mtext">Join Project</span>
          </a>
        </li>
        {% if show_tabs %}
          <li class="nav-item pcoded-hasmenu">
            <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i 
              class="feather icon-layers"></i></span><span class="pcoded-mtext">{{ project.title }}</span></a>
            <ul class="pcoded-submenu">
              <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" class="nav-item">
                <a href="{% url 'tasks:project-task-list' pk=project.id %}" class="nav-link ">
                  <span class="pcoded-micon"><i class="feather icon-server"></i></span><span class="pcoded-mtext">Project Tasks</span>
                </a>
              </li>
              <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" class="nav-item">
                <a href="{% url 'tasks:task-list' pk=project.id %}" class="nav-link ">
                  <span class="pcoded-micon"><i class="feather icon-briefcase"></i></span><span class="pcoded-mtext">Your Tasks</span>
                </a>
              </li>
              <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" class="nav-item">
                <a href="{% url 'tasks:project-chat' pk=project.id %}" class="nav-link ">
                  <span class="pcoded-micon"><i class="feather icon-message-square"></i></span><span class="pcoded-mtext">Chat</span>
                </a>
              </li>
            </ul>
          </li>
        {% endif %}

        {% if not request.user.is_authenticated %}
        <li
          data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
          class="nav-item pcoded-hasmenu">
          <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i
                class="feather icon-lock"></i></span><span class="pcoded-mtext">Authentication</span></a>
          <ul class="pcoded-submenu">
            <li class=""><a href="{% url 'tasks:login' %}" class="">Sign IN</a></li>
            <li class=""><a href="{% url 'tasks:register' %}" class="">Sign UP</a></li>
          </ul>
        </li>
        {% else %}
          <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe" class="nav-item pcoded-hasmenu">
            <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span class="pcoded-mtext">Authentication</span></a>
            <ul class="pcoded-submenu">
              <li><a href="{% url 'tasks:logout' %}?next=/" target="_blank">Log out</a></li>
            </ul>
          </li>
          <li data-username="Profile Page" class="nav-item {% if 'profile' in segment %}active{% endif %}">
            <a href="{% url 'tasks:profile-detail' %}" class="nav-link"><span class="pcoded-micon"><i class="feather icon-user"></i></span><span class="pcoded-mtext">Profile Page</span></a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>