task_manager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve

from task_manager import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls"))
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += [
    re_path(r"^media/(?P<path>.*)$", serve, {
        "document_root": settings.MEDIA_ROOT
    })
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path("__debug__/", include(debug_toolbar.urls)),

tasks/urls.py
from django.urls import path

from tasks.views import (
    UserLoginView,
    UserRegistrationView,
    UserPasswordChangeView,
    ProjectListView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TaskCreateView,
    ProjectTaskListView,
    ProfileDetailView,
    ProfileUpdateView,
    TaskListView,
    TaskDetailView,
    ProjectDetailView,
    JoinProjectView,
    GenerateCodeView,
    ChatMessagesView,
    LogoutView,
    TaskUpdateView,
    TaskDeleteView,
    IndexView
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("accounts/login/", UserLoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/register/", UserRegistrationView.as_view(), name="register"),
    path("accounts/password-change/", UserPasswordChangeView.as_view(), name="password-change"),
    path("projects/",
         ProjectListView.as_view(),
         name="project-list"
         ),
    path("projects/<int:pk>/",
         ProjectDetailView.as_view(),
         name="project-detail"
         ),
    path("projects/<int:pk>/project_tasks/",
         ProjectTaskListView.as_view(),
         name="project-task-list"),
    path("projects/<int:pk>/tasks/",
         TaskListView.as_view(),
         name="task-list"),
    path("projects/<int:pk>/tasks/<int:task_pk>/",
         TaskDetailView.as_view(),
         name="task-detail"),
    path("projects/<int:pk>/tasks/add/",
         TaskCreateView.as_view(),
         name="task-add"),
    path("projects/<int:pk>/tasks/<int:task_pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"),
    path("projects/<int:pk>/tasks/<int:task_pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),
    path("projects/create/",
         ProjectCreateView.as_view(),
         name="project-create"
         ),
    path("projects/<int:pk>/update/",
         ProjectUpdateView.as_view(),
         name="project-update"
         ),
    path("projects/<int:pk>/delete/",
         ProjectDeleteView.as_view(),
         name="project-delete"),
    path("projects/<int:pk>/invitation/",
         GenerateCodeView.as_view(),
         name="project-invitation"),
    path("projects/join/",
         JoinProjectView.as_view(),
         name="project-join"),
    path("projects/<int:pk>/chat/",
         ChatMessagesView.as_view(),
         name="project-chat"),
    path("profile/",
         ProfileDetailView.as_view(),
         name="profile-detail"
         ),
    path("profile/edit/",
         ProfileUpdateView.as_view(),
         name="profile-edit")
]

app_name = "tasks"

tasks/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from task_manager import settings


class Position(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    profile_image = models.ImageField(upload_to="profile_pictures", blank=True)
    position = models.ForeignKey(Position, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Project(models.Model):
    title = models.CharField(max_length=63)
    description = models.TextField()
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="projects")
    invitation_code = models.UUIDField(editable=False, unique=True, null=True, blank=True)

    class Meta:
        ordering = ("title", )

    def get_absolute_url(self):
        return reverse("tasks:project-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.title} - creator: {self.creator}"


class Task(models.Model):
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"

    PRIORITY_CHOICES = [
        (HIGH, "High"),
        (MEDIUM, "Medium"),
        (LOW, "Low"),
    ]

    TODO = "To do"
    DOING = "Doing"
    DONE = "Done"

    STATUS_CHOICES = [
        (TODO, "To do"),
        (DOING, "Doing"),
        (DONE, "Done"),
    ]

    name = models.CharField(max_length=63)
    description = models.TextField()
    deadline = models.DateField(null=True, blank=True)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default=MEDIUM)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=TODO)
    task_type = models.ForeignKey(TaskType,
                                  related_name="tasks",
                                  on_delete=models.SET_NULL,
                                  null=True)
    modified = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.name} {self.deadline}"

    def get_absolute_url(self):
        return reverse("tasks:task-detail", kwargs={"pk": self.project.pk, "task_pk": self.pk})


class ChatMessage(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="messages")
    message = models.TextField()
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


class TaskComment(models.Model):
    message = models.TextField()
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="comments")

    class Meta:
        ordering = ("-date", )

tasks/views.py
import uuid

from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.db.models import Q

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic, View
from django.http import HttpResponseForbidden

from tasks.forms import (
    RegistrationForm,
    LoginForm,
    ProjectForm,
    UserPasswordChangeForm,
    JoinProjectForm,
    ChatMessageForm,
    ProjectSearchForm,
    TaskForm,
    CommentForm,
    ProjectTaskSearchForm,
    ProfileForm
)
from tasks.models import (
    Task,
    Project,
    ChatMessage,
    TaskComment,
    Worker
)


class IndexView(generic.View):
    template_name = "tasks/index.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user_projects = Project.objects.filter(
                Q(creator=request.user) | Q(assignees=request.user)
            ).distinct()

            project_ids = set(user_projects.values_list('id', flat=True))
            num_projects = len(project_ids)
            num_tasks = Task.objects.filter(creator=request.user).count()

            context = {
                "num_projects": num_projects,
                "num_tasks": num_tasks
            }

            return render(request, self.template_name, context)

        return render(request, self.template_name)


class UserLoginView(LoginView):
    template_name = "accounts/login.html"
    form_class = LoginForm


class LogoutView(View):
    @staticmethod
    def get(request, *args, **kwargs):
        logout(request)

        return redirect("/")


class UserRegistrationView(generic.CreateView):
    template_name = "accounts/signup.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("tasks:login")


class UserPasswordChangeView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("tasks:login")
    template_name = "accounts/change_password.html"


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "tasks/task_list.html"
    context_object_name = "task_list"

    def get_queryset(self):
        project = get_object_or_404(Project, id=self.kwargs["pk"])
        queryset = super().get_queryset().filter(project=project, creator=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = get_object_or_404(Project, id=self.kwargs["pk"])
        context["project"] = project
        context["show_tabs"] = True

        return context


class ProjectTaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "tasks/project_task_list.html"
    context_object_name = "project_tasks"
    paginate_by = 10

    def get_queryset(self):
        project = get_object_or_404(Project, id=self.kwargs["pk"])
        queryset = super().get_queryset().filter(project=project)
        search_query = self.request.GET.get("title", None)
        if search_query:
            queryset = queryset.filter(name__icontains=search_query)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = get_object_or_404(Project, id=self.kwargs["pk"])
        context["project"] = project
        context["search_form"] = ProjectTaskSearchForm()
        context["show_tabs"] = True
        context["show_search"] = True

        return context

    def dispatch(self, request, *args, **kwargs):
        project = get_object_or_404(Project, id=self.kwargs["pk"])
        if request.user in project.assignees.all() or request.user == project.creator:
            return super().dispatch(request, *args, **kwargs)

        return HttpResponseForbidden("You do not have permission to view this page.")


class TaskDetailView(LoginRequiredMixin, generic.View):
    @staticmethod
    def get(request, pk, task_pk):
        project = get_object_or_404(Project, pk=pk)
        task = get_object_or_404(Task, id=task_pk)
        comments = TaskComment.objects.filter(task=task)
        if request.user not in project.assignees.all():
            return HttpResponseForbidden("You do not have permission to this page.")
        form = CommentForm()
        context = {
            "form": form,
            "task": task,
            "project": project,
            "show_tabs": True,
            "comments": comments
        }

        return render(request, "tasks/task_detail.html", context)

    @staticmethod
    def post(request, pk, task_pk):
        project = get_object_or_404(Project, pk=pk)
        task = get_object_or_404(Task, id=task_pk)
        comments = TaskComment.objects.filter(task=task)
        if request.user not in project.assignees.all():
            return HttpResponseForbidden("You do not have permission to this page.")
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.sender = request.user
            comment.task = task
            comment.save()
        else:
            form = CommentForm()
        context = {
            "form": form,
            "task": task,
            "project": project,
            "show_tabs": True,
            "comments": comments
        }

        return render(request, "tasks/task_detail.html", context)


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    template_name = "tasks/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")

    def form_valid(self, form):
        form.instance.creator_id = self.request.user.id
        form.instance.project_id = self.kwargs["pk"]
        self.success_url = reverse_lazy("tasks:task-list", kwargs={"pk": self.kwargs["pk"]})

        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, generic.View):
    @staticmethod
    def get(request, pk, task_pk):
        project = get_object_or_404(Project, pk=pk)
        task = get_object_or_404(Task, id=task_pk)

        if request.user != task.creator:
            return HttpResponseForbidden("You do not have permission to this page.")

        form = TaskForm(instance=task)

        context = {
            "form": form,
            "project": project,
            "task": task,
            "show_tabs": True
        }

        return render(request, "tasks/task_form.html", context)

    @staticmethod
    def post(request, pk, task_pk):
        project = get_object_or_404(Project, pk=pk)
        task = get_object_or_404(Task, id=task_pk)

        if request.user != task.creator:
            return HttpResponseForbidden("You do not have permission to this page.")

        form = TaskForm(request.POST, instance=task)

        if form.is_valid():
            form.instance.creator_id = request.user.id
            form.instance.project_id = pk
            form.save()

            return redirect("tasks:task-list", pk=pk)

        context = {
            "form": form,
            "project": project,
            "task": task,
            "show_tabs": True
        }

        return render(request, "tasks/task_form.html", context)


class TaskDeleteView(LoginRequiredMixin, generic.View):
    @staticmethod
    def post(request, pk, task_pk):
        task = get_object_or_404(Task, id=task_pk)

        if request.user != task.creator:
            return HttpResponseForbidden("You do not have permission to this page.")

        task.delete()

        return redirect("tasks:task-list", pk=pk)

    @staticmethod
    def get(request, pk, task_pk):
        project = get_object_or_404(Project, pk=pk)
        task = get_object_or_404(Task, id=task_pk)

        context = {
            "project": project,
            "task": task,
            "show_tabs": True
        }

        return render(request, "tasks/task_confirm_delete.html", context)


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    queryset = Project.objects.all()
    context_object_name = "project_list"
    template_name = "tasks/project_list.html"
    paginate_by = 3

    def get_queryset(self):
        user = self.request.user
        queryset = Project.objects.filter(Q(creator=user) | Q(assignees=user)).distinct()

        form = ProjectSearchForm(self.request.GET)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            queryset = queryset.filter(title__icontains=title)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = ProjectSearchForm(
            initial={"title": title}
        )
        context["show_search"] = True

        return context


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    template_name = "tasks/project_detail.html"
    context_object_name = "project"

    def dispatch(self, request, *args, **kwargs):
        if request.user == self.get_object().creator or request.user in self.get_object().assignees.all():
            return super().dispatch(request, *args, **kwargs)

        return HttpResponseForbidden("You do not have permission to this page")

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["show_tabs"] = True
        context["project"] = self.object

        return context


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    template_name = "tasks/project_form.html"
    form_class = ProjectForm
    success_url = reverse_lazy("tasks:project-list")

templates/tasks/index.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  {% if request.user.is_authenticated %}
  <div class="row">
    <div class="col-md-6 col-xl-4">
      <div class="card daily-sales">
        <div class="card-block">
          <h6 class="mb-4">Your Projects</h6>
          <div class="row d-flex align-items-center">
            <div class="col-9">
              <h3 class="f-w-300 d-flex align-items-center m-b-0">
                {{ num_projects }}
              </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-xl-4">
      <div class="card Monthly-sales">
        <div class="card-block">
          <h6 class="mb-4">Your Tasks</h6>
          <div class="row d-flex align-items-center">
            <div class="col-9">
              <h3 class="f-w-300 d-flex align-items-center  m-b-0">
                {{ num_tasks }}
              </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% else %}
    <h2><a href="{% url 'tasks:login' %}">Log in</a> to view your count of projects and tasks.</h2>
  {% endif %}
{% endblock %}

templates/tasks/profile_detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="page-header-title">
      <h2 class="m-b-20">
        Your Profile
      </h2>
    </div>
    <div class="row">
      <div class="col-xl-4 col-md-6">
        <div class="card card-event">
          <div class="card-block">
            <div class="row align-items-center justify-content-center">
              <div class="col">
                {% if user.profile_image and user.profile_image.url %}
                  <img src="{{ user.profile_image.url }}" class="img-avatar" alt="User-Profile-Image">
                {% else %}
                  <img src="{% static 'assets/images/user/anon.jpg' %}" class="img-avatar" alt="User-Profile-Image">
                {% endif %}
                <h5 class="m-0">{{ user.get_username }}</h5>
              </div>
            </div>
            <h6 class="text-muted mt-4 mb-0"><a href="{% url 'tasks:profile-edit' %}" class="btn btn-warning">Edit</a></h6>
            <i class="fab fa-osi text-c-purple f-50"></i>
          </div>
        </div>
      </div>
      <div class="col-xl-8 col-md-6">
        <div class="card Recent-Users">
          <div class="card-header">
              <h5>Information</h5>
          </div>
          <div class="card-block px-0 py-3">
            <div class="table-responsive">
              <table class="table table-hover">
                <tbody>
                  <tr class="unread">
                    <td>
                      <h6 class="mb-1">Full name</h6>
                    </td>
                    <td>
                      <h6 class="text-muted">{{ user.first_name }} {{ user.last_name }}</h6>
                    </td>
                  </tr>
                  <tr class="unread">
                    <td>
                      <h6 class="mb-1">Email</h6>
                    </td>
                    <td>
                      <h6 class="text-muted">{{ user.email }}</h6>
                    </td>
                  </tr>
                  <tr class="unread">
                    <td>
                        <h6 class="mb-1">Position</h6>
                    </td>
                    <td>
                        <h6 class="text-muted">{{ user.position }}</h6>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/tasks/profile_form.html
{% extends "layouts/base.html" %}

{% block content %}

  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">
          <h5>Edit Profile</h5>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <form action="" method="post" novalidate enctype="multipart/form-data">
                {% csrf_token %}
                  {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/tasks/project_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>Delete project?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/project_detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="page-header-title">
      <h2 class="m-b-20">{% if user == project.creator %}Your{% endif %} Project
        {% if user == project.creator %}
          <a href="{% url 'tasks:project-invitation' pk=project.id %}" class="btn btn-primary float-right">Invite</a>
        {% endif %}
      </h2>
    </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="card">
            <div class="card-header">
              <h5>
                {{ project.title }}
              </h5>
            </div>
            <div class="card-block table-border-style">
              <span>{{ project.description }}</span>
            </div>
            <div class="card-block table-border-style">
              <span>
                Assignees: {{ project.assignees.count }}
              </span>
            </div>
          </div>
        </div>
      </div>
    {% if user == project.creator %}
      <span>
        <a href="{% url 'tasks:project-update' pk=project.id %}" class="btn btn-warning link-to-page">
          Update
        </a>
        <a href="{% url 'tasks:project-delete' pk=project.id %}" class="btn btn-danger link-to-page">
          Delete
        </a>
      </span>
    {% endif %}
  {% endif %}
{% endblock %}

templates/tasks/project_form.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">
          <h5>{{ object|yesno:"Update,Create" }} Project</h5>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <form action="" method="post" novalidate>
                {% csrf_token %}
                  <label>Title</label>
                  {{ form.title }}
                  <label for="exampleFormControlTextarea1">Description</label>
                  {{ form.description }}
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/tasks/project_invitation.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="page-header-title">
      <h2 class="m-b-20">Invitation Code</h2>
    </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="card">
            <div class="card-header">
              <h5>
                {{ project.invitation_code }}
              </h5>
            </div>
          </div>
        </div>
      </div>
  {% endif %}
{% endblock %}

templates/tasks/project_join_form.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="page-header-title">
      <h2 class="m-b-20">Join project</h2>
    </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="card">
            <div class="card-header">
              {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
              <form action="" method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                  {{ form.invitation_code }}
                </div>
                <button type="submit" class="btn btn-primary">Join</button>
              </form>
            </div>
          </div>
        </div>
      </div>
  {% endif %}
{% endblock %}

templates/tasks/project_list.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="page-header-title">
        <h2 class="m-b-20">Projects
            <a href="{% url 'tasks:project-create' %}" class="btn btn-primary float-right">Create</a>
        </h2>
    </div>
    {% if project_list %}
      {% for project in project_list %}
        <div class="row">
            <div class="col-xl-12">
              <div class="card">
                <div class="card-header">
                  <h5>
                    <a href="{% url 'tasks:project-detail' pk=project.id %}">{{ project.title }}</a>
                  </h5>
                  <div class="col-xl-22">
                    <h6>Creator: {{ project.creator }}</h6>
                  </div>
                </div>
                <div class="card-block table-border-style">
                  <span>{{ project.description }}</span>
                </div>
                <div class="card-block table-border-style">
                  <span>
                    Assignees: {{ project.assignees.count }}
                  </span>
                </div>
              </div>
            </div>
        </div>
      {% endfor %}
    {% else %}
      <h1>You don't have any project</h1>
    {% endif %}
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/task_detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="page-header-title">
      <h2 class="m-b-20">{% if user == task.creator %}Your{% else %}{{ task.creator.username }}'s{% endif %} Task
        {% if user == task.creator %}
          <a href="{% url 'tasks:task-update' pk=project.id task_pk=task.id %}" class="btn btn-primary float-right">Edit</a>
        {% endif %}
      </h2>
    </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="card">
            <div class="card-header">
              <h5>
                {{ task.name }}
              </h5>
            </div>
            <div class="card-block table-border-style">
              <p>Description:</p>
              <span>{{ task.description }}</span>
            </div>
            <div class="card-block table-border-style">
              <p>Deadline:</p>
              <p>{{ task.deadline }}</p>
            </div>
            <div class="card-block table-border-style">
              <p>Priority:</p>
              <p>{{ task.priority }}</p>
            </div>
            <div class="card-block table-border-style">
              <p>Status:</p>
              <p>{{task.status}}</p>
            </div>
            <div class="card-block table-border-style">
              <p>Task type:</p>
              <p>{{ task.task_type }}</p>
            </div>
          </div>
        </div>
      </div>
    {% if user == task.creator %}
      <span>
        <a href="{% url 'tasks:task-delete' pk=project.id task_pk=task.id %}" class="btn btn-danger link-to-page">
          Delete
        </a>
      </span>
    {% endif %}
    {% include "includes/comments.html" %}
  {% endif %}
{% endblock %}

templates/tasks/task_form.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">
          <h5>{{ object|yesno:"Update,Create" }} Task</h5>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <form action="" method="post" novalidate>
                {% csrf_token %}
                  {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/tasks/task_list.html
{% extends "layouts/base.html" %}

{% block content %}
      <div class="page-header-title">
        <h2 class="m-b-20">Your Tasks
            <a href="{% url 'tasks:task-add' pk=project.id %}" class="btn btn-primary float-right">Add</a>
        </h2>
      </div>
      <ul class="tasks__list">
        <li class="tasks__list-item">
          <ul class="tasks__list-type">
            <li class="tasks__list-type-status">To do</li>
            {% if task_list %}
              {% for task in task_list %}
                {% if task.status == "To do" %}
                  <li class="tasks__list-type-task {% if task.priority == 'Low' %} low-priority {% elif task.priority == 'Medium' %} medium-priority {% elif task.priority == 'High' %} high-priority {% endif %}">
                    <a href="{% url 'tasks:task-detail' pk=project.id task_pk=task.id %}">{{ task.name }}</a>
                    <p>({{ task.deadline }})</p>
                  </li>
                  <hr style="border:2px solid white; width: 80%">
                {% endif %}
              {% endfor %}
            {% endif %}
          </ul>
        </li>
        <li class="tasks__list-item">
          <ul class="tasks__list-type">
            <li class="tasks__list-type-status">Doing</li>
            {% if task_list %}
              {% for task in task_list %}
                {% if task.status == "Doing" %}
                  <li class="tasks__list-type-task {% if task.priority == 'Low' %} low-priority {% elif task.priority == 'Medium' %} medium-priority {% elif task.priority == 'High' %} high-priority {% endif %}">
                    <a href="{% url 'tasks:task-detail' pk=project.id task_pk=task.id %}">{{ task.name }}</a>
                    <p>({{ task.deadline }})</p>
                  </li>       
                  <hr style="border:2px solid white; width: 80%">
                {% endif %}
              {% endfor %}
            {% endif %}
          </ul>
        </li>
        <li class="tasks__list-item">
          <ul class="tasks__list-type">
            <li class="tasks__list-type-status">Done</li>
            {% if task_list %}
              {% for task in task_list %}
                {% if task.status == "Done" %}
                  <li class="tasks__list-type-task done-task">
                    <a href="{% url 'tasks:task-detail' pk=project.id task_pk=task.id %}">{{ task.name }}</a>
                    <p>({{ task.deadline }})</p>
                  </li>
                  <hr style="border:2px solid white; width: 80%">
                {% endif %}
              {% endfor %}
            {% endif %}
          </ul>
        </li>
      </ul>
{% endblock %}